[build]
  command = "npm run build"
  publish = "out"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "16" # Matches your current Node.js version
  NPM_VERSION = "8.19.4"
